echo "- Improve WiFi/Mobile Data speeds"
DELETE_FROM_WORK_DIR "product" "app/ConnectivityUxOverlay"
DELETE_FROM_WORK_DIR "product" "app/NetworkStackOverlay"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "product" "app/ConnectivityUxOverlay" 0 0 755 "u:object_r:system_file:s0"
ADD_TO_WORK_DIR "$TARGET_FIRMWARE" "product" "app/NetworkStackOverlay" 0 0 755 "u:object_r:system_file:s0"
